### PR TITLE
fix: decorate items[itemname], event.item, and triggered item

### LINKED ISSUE #58: Convert all items to delegate rather than monkeypatching
Discussed in #47 and #48 
Also need to wrap when coming back from framework on rule triggers.

### PR DESCRIPTION
**Pull request by jimtng**
This task is mentioned in #58

### CODE REVIEW

File: lib/openhab/core/dsl/rule/automation_rule.rb [hunk 1]
```diff
@@ -237,6 +237,19 @@ class << event
...
 
+          #
+          # Patch event to decorate event.item with our item wrapper
+          #
+          # @param [OpenHAB Event] event patch
+          #
+          def decorate_event_item(event)
+            class << event
+              def item
+                EntityLookup.decorate_items(super).first
```
Comment (pacive) [inline lib/openhab/core/dsl/rule/automation_rule.rb:248]: Would it make sense to split the `EntityLookup.decorate_items` method into two methods: `::decorate_items` that take an array of items, and `::decorate_item` that takes a single item (and is called by `::decorate_items` for each item)? Then you could call the second method directly here.

Comment (jimtng) [reply lib/openhab/core/dsl/rule/automation_rule.rb]: Good idea!

**Comment by jimtng** [comment]
I modified the way event.item is wrapped by calling items[item_name]. However, this depends on the fix in #148 which should be merged first. Also this now eliminates the need for #87
