### PR TITLE
fix(monthday): fix monthday error when rolling over to another year

### LINKED ISSUE #479: MonthDay range doesn't properly adjust ending_year/current_year
This code:
```
# Wrap to next year if ending day of month is before starting day of month
ending_year = ending < start ? next_year : current_year
```
Doesn't work correctly. 
1. It adjust ending year when it shouldn't -- right now it always increments the ending year even in cases when it shouldn't. e.g. 12/31 and 1/2 when testing on today (1/1) should be 12/31/2021 and 1/2/2022.  Instead it is 12/31/2022 and 1/2/2023.
2. There is no method to adjust backwards the starting_year. 

The current year needs to play into the decision about the start and end year. 

I don't quite know what the algorithm should be.  @ccutrer or @jimtng not sure if either of you have ideas on what the algorithm is.  I looked at it for a few minute and it didn't jump off the page to me.  I might come back after a break and see if that helps.

### PR DESCRIPTION
**Pull request by boc-tothefuture**
Closes #479

Take a different approach (ignoring year) than #480

@jimtng are you ok with this approach?

### CODE REVIEW

File: lib/openhab/dsl/time/month_day.rb [hunk 1]
```diff
@@ -8,40 +10,21 @@ module Between
...
-
-          # Wrap to next year if ending day of month is before starting day of month
-          ending_year = ending < start ? next_year : current_year
+          start_range = DayOfYear.new(month_day: start, range: start..ending)
+          ending_range = DayOfYear.new(month_day: ending, range: start..ending)
+          logger.trace "Month Day Range Start(#{start}) - End (#{ending}) - Created from (#{range})"
 
-          start_range = MonthDayRangeElement.new(month_day: start, year: current_year)
-          ending_range = MonthDayRangeElement.new(month_day: ending, year: ending_year)
           range.exclude_end? ? (start_range...ending_range) : (start_range..ending_range)
```
Comment (jimtng) [inline lib/openhab/dsl/time/month_day.rb:26]: Not a suggestion, just a question for my edification: why is the above preferred to:
```ruby
Range.new(start_range, ending_range, range.exclude_end?)
```

File: lib/openhab/dsl/time/month_day.rb [hunk 2]
```diff
@@ -52,54 +35,80 @@ def self.range?(range)
...
           end
-          # rubocop:enable Metrics/AbcSize
+        end
+      end
+
+      java_import java.time.Month
+      # Extend Month with helper method
+      class Month
+        # Calcalute and memoize the maximum number of days in a year before this month
+        # @return [Number] maximum nummber of days in a year before this month
```
Comment (jimtng) [inline lib/openhab/dsl/time/month_day.rb:109]:
```suggestion
        # Calculate and memoize the maximum number of days in a year before this month
        # @return [Number] maximum number of days in a year before this month
```

File: lib/openhab/dsl/time/month_day.rb [hunk 3]
```diff
@@ -52,54 +35,80 @@ def self.range?(range)
...
+        def max_days_before
+          @max_days_before ||= Month.values.select { |month| month < self }.sum(&:max_length)
```
Comment (jimtng) [inline lib/openhab/dsl/time/month_day.rb:111]: This would save us from running the select loop, perhaps at the expense of readability - your call
```suggestion
          @max_days_before ||= Month.values.sum(&:max_length) - max_length
```

**Review by jimtng — COMMENTED** [review]
This is a great and neat implementation. I like it.
