### PR TITLE
fix(comparisons): === should perform an exact type match for case statements

### LINKED ISSUE #365: Case comparisons are sensitive to specific sequence
Here are some tests that are currently failing. 

```
  Scenario Outline: event.command for Color item can be compared to accepted command types
    Given items:
      | type  | name  |
      | Color | Item1 |
    And a rule
      """
      rule 'handle command' do
        received_command Item1
        run do |event|
          logger.info('We sent a command <command>')
          logger.info("event.command.class: #{event.command.class}")
          log = case event.command
                when <cond1> then 'cond1'
                when <cond2> then 'cond2'
                when <cond3> then 'cond3'
                else 'cond-else'
                end
          logger.info("case match: #{log}")
        end
      end
      """
    When I deploy the rule
    And item "Item1" state is changed to "<command>"
    Then It should log 'case match: <log>' within 5 seconds
    Examples:
      | command  | cond1       | cond2             | cond3    | log   |
      | ON       | ON          | 1..100            | INCREASE | cond1 |
      | ON       | 0..99,100   | OFF               | ON       | cond3 |
      | OFF      | OFF         | INCREASE,DECREASE | 0        | cond1 |
      | OFF      | 1..100      | 0                 | OFF      | cond3 |
      | INCREASE | ON,DECREASE | 0..100            | INCREASE | cond3 |
      | DECREASE | OFF         | 0,INCREASE        | DECREASE | cond3 |
      | 0        | OFF         | DECREASE          | 0        | cond3 |
      | 0        | ON          | DECREASE          | 0..50    | cond3 |
      | 50       | ON          | INCREASE          | 50       | cond3 |
      | 100      | ON          | 0..99             | 100      | cond3 |
      | 100      | ON          | 0..99             | 100      | cond3 |
      | 1,2,3    | 1,2,3       | 0.100             | OFF      | cond1 |
      | 1,2,3    | ON          | 0.100             | '1,2,3'  | cond3 |

  Scenario Outline: event.command for Player item can be compared to accepted command types
    Given items:
      | type   | name  |
      | Player | Item1 |
    And a rule
      """
      rule 'handle command' do
        received_command Item1
        run do |event|
          logger.info('We sent a command <command>')
          logger.info("event.command.class: #{event.command.class}")
          log = case event.command
                when <cond1> then 'cond1'
                when <cond2> then 'cond2'
                when <cond3> then 'cond3'
                else 'cond-else'
                end
          logger.info("case match: #{log}")
        end
      end
      """
    When I deploy the rule
    And item "Item1" state is changed to "<command>"
    Then It should log 'case match: <log>' within 5 seconds
    Examples:
      | command | cond1 | cond2                            | cond3 | log   |
      | PLAY    | PLAY  | 1..100                           | ON    | cond1 |
      | PLAY    | PAUSE | NEXT,PREVIOUS,REWIND,FASTFORWARD | PLAY  | cond3 |

  Scenario Outline: event.command for Rollershutter item can be compared to accepted command types
    Given items:
      | type          | name  |
      | Rollershutter | Item1 |
    And a rule
      """
      rule 'handle command' do
        received_command Item1
        run do |event|
          logger.info('We sent a command <command>')
          logger.info("event.command.class: #{event.command.class}")
          log = case event.command
                when <cond1> then 'cond1'
                when <cond2> then 'cond2'
                when <cond3> then 'cond3'
                else 'cond-else'
                end
          logger.info("case match: #{log}")
        end
      end
      """
    When I deploy the rule
    And item "Item1" state is changed to "<command>"
    Then It should log 'case match: <log>' within 5 seconds
    Examples:
      | command | cond1     | cond2     | cond3   | log   |
      | UP      | 0         | 1..100    | DOWN,UP | cond3 |
      | UP      | 100       | STOP,MOVE | UP      | cond3 |
      | STOP    | STOP      | MOVE      | 0       | cond1 |
      | MOVE    | STOP      | UP,DOWN   | MOVE    | cond3 |
      | 0       | STOP,MOVE | UP,DOWN   | 0       | cond3 |
      | 100     | STOP,MOVE | 100       | DOWN    | cond2 |
```

PS I didn't include DimmerItem because I figured the tests for ColorItem already cover the same types for it.

_Originally posted by @jimtng in https://github.com/boc-tothefuture/openhab-jruby/issues/332#issuecomment-953370755_

### PR DESCRIPTION
**Pull request by jimtng**
Resolve #365 

**This could potentially be a breaking change.**

`case` comparisons must now use the underlying type.

Case in point:
```ruby
RollerShutterItem1 << DOWN
case RollerShutterItem1
when DOWN then logger.info("It will no longer reach here")
when 100 then logger.info("It will reach here: 100")
end
```

I believe this is the correct / non ambiguous behaviour. It also allows precision handling of commands sent to items that support multiple types, which is the whole reason for this PR.

Example:
```ruby
rule 'x' do
  received_command RollerShutterItem1
  run do |event|
    case event.command
    when 0..100 then logger.info("A specific position has been commanded")
    when DOWN then logger.info("DOWN command received")
    end
  end
end

RollerShutterItem1 << DOWN
```

The following will still evaluate to true, as it's not affected by this PR: `RollerShutterItem1 == 100`, `RollerShutterItem1 == DOWN` or `RollerShutterItem1.down?`

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Makes sense to me. 
@ccutrer ?

**Comment by jimtng** [comment]
I still have a few kinks to work out to pass all tests, but the general concept is the same.

File: lib/openhab/dsl/types/type.rb [hunk 1]
```diff
@@ -41,6 +41,20 @@ def eql?(other)
...
+        #
+        # Case equality
+        #
+        # @return [Boolean] if the values are of the same Type
+        #                   or item state of the same type
+        #
+        def ===(other)
+          logger.trace("(#{self.class}) #{self} === #{other} (#{other.class})")
+          other = other.state if other.respond_to?(:state)
+          return false unless is_a?(other.class)
```
Comment (ccutrer) [inline lib/openhab/dsl/types/type.rb:53]: instead of calling is_a? (you should really be using instance_of? in this case) and calling super, just call `eql?(other)` at this point

**Review by ccutrer — COMMENTED** [review]
while it's a bit opposite of normal (usually === is broader than ==) it makes sense in this case.

File: lib/openhab/dsl/types/type.rb (hunk 1 above)
Comment (jimtng) [reply lib/openhab/dsl/types/type.rb:53]: Thanks for the suggestions. I'll implement them in the next push.

File: features/groups.feature [hunk 2]
```diff
@@ -152,8 +152,8 @@ Feature:  groups
       end
 
       case Shutters
-      when UP then logger.info('All shutters are UP')
-      when DOWN then logger.info('At least one shutter is not UP')
+      when 0 then logger.info('All shutters are UP')
+      when 100 then logger.info('At least one shutter is not UP')
```
Comment (jimtng) [inline features/groups.feature:156]: This part here is a bit counter-intuitive. The comparison in a case statement for item `state` (as opposed to `command`) also requires an exact type match, in this case, because the state's type is PercentType, it must be compared against PercentType.

**Comment by jimtng** [comment]
This is ready for review

**Review by ccutrer — APPROVED** [review]

File: features/groups.feature (hunk 2 above)
Comment (boc-tothefuture) [reply features/groups.feature:156]: Does that need to be in the docs so we and others don't get confused?

Comment (jimtng) [reply features/groups.feature:156]: > Does that need to be in the docs so we and others don't get confused?

Ideally, we'll have a page that comprehensively explains about how state comparisons work in various different ways. For example, how and why PercentType.new(1).on? returns true vs PercentType.new(1) === ON returns false. 

I'll create a separate PR for that because I may not think of all possible scenarios.

**Comment by jimtng** [comment]
Should this be flagged as a breaking change?

**Comment by boc-tothefuture** [comment]
> Should this be flagged as a breaking change?

That is a judgement call.  Is this a fix of something broken or a broken change.  The API surface isn't changing so I am inclined to call it a fix, but will defer to you.

**Comment by jimtng** [comment]
> > Should this be flagged as a breaking change?
> 
> That is a judgement call. Is this a fix of something broken or a broken change. The API surface isn't changing so I am inclined to call it a fix, but will defer to you.

I'm happy to call it a fix too.
